modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="delbase"
version="${file.jarVersion}"
displayName="DePhoegons' Base Blocks"
logoFile="dephoegonlogo.png"
credits="Lack of Sanity, Myself, Trial & Error, Family, and My friend(s) for listening to insanity."
authors="DePhoegon"
description='''
This is a decoration & resource reclaimation mod.
The astehtic of the pack is meant to be in-line the base game visuals.
The resource reclaimation aspects are designed around non-modded armors. Support/patch mods will be needed to extend to modded items/materials.
'''
[[dependencies.delbase]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.delbase]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
